.TH LSGRP 1
.SH NAME
lsgrp \- list the members of a group
.SH SYNOPSIS
.B lsgrp
[
.I groupname
]
.SH DESCRIPTION
.I Lsgrp
lists the members of the group
.I groupname
on the standard output.
.SH SOURCE
.B https://github.com/frithjof-schulze/lsgrp
\.".SH SEE ALSO
\.".IR cp (1) there should be some similar tools around
.SH DIAGNOSTICS
.I Lsgrp
exits with status
.B 1
if the given group does not exists and with status
.B 2
if any other error occurs.
.SH BUGS
None knowen.
